### ISSUE TITLE
How can i made one column not filterable in table

### ISSUE THREAD

**Issue by devikatopnotch** [lightswitch05/filterable#14]
This is a great work with filterable for each column in table. But i don't need that filterable option for first column in my table that is serial number column.How can i disable the filterable option for particular column.Help.

**Comment by chrisjohnstone** [comment]
You can use the `ignoreColumns` option.

```
$('#table-id').filterable({
	ignoreColumns: [1, 5],
});
```

Remeber the first column will be '0'

http://lightswitch05.github.io/filterable/ for more.

**Comment by lightswitch05** [comment]
Thanks @chrisjohnstone for answering this one. Closing ticket.
